export const expeditionDB = [
  // --- 第 1 海域：鎮守府海域 ---
  {
    id: "1",
    area: "1",
    name: "練習航海",
    duration: 15,
    fuel: 0,
    ammo: 30,
    steel: 0,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "2",
    area: "1",
    name: "長距離練習航海",
    duration: 30,
    fuel: 0,
    ammo: 100,
    steel: 30,
    bauxite: 0,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "水桶"],
  },
  {
    id: "3",
    area: "1",
    name: "警備任務",
    duration: 20,
    fuel: 30,
    ammo: 30,
    steel: 40,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "4",
    area: "1",
    name: "対潜警戒任務",
    duration: 50,
    fuel: 0,
    ammo: 70,
    steel: 0,
    bauxite: 0,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "水桶"],
  },
  {
    id: "5",
    area: "1",
    name: "海上護衛任務",
    duration: 90,
    fuel: 200,
    ammo: 200,
    steel: 20,
    bauxite: 20,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "燃料", "彈藥"],
  },
  {
    id: "6",
    area: "1",
    name: "防空射撃演習",
    duration: 40,
    fuel: 0,
    ammo: 0,
    steel: 0,
    bauxite: 80,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "鋁土"],
  },
  {
    id: "7",
    area: "1",
    name: "観艦式予行",
    duration: 60,
    fuel: 0,
    ammo: 0,
    steel: 50,
    bauxite: 30,
    bucket: 0,
    torch: 1,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "8",
    area: "1",
    name: "観艦式",
    duration: 180,
    fuel: 50,
    ammo: 100,
    steel: 50,
    bauxite: 50,
    bucket: 0,
    torch: 2,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "A1",
    area: "1",
    name: "兵站強化任務",
    duration: 25,
    fuel: 45,
    ammo: 45,
    steel: 0,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "A2",
    area: "1",
    name: "海峡警備行動",
    duration: 55,
    fuel: 70,
    ammo: 40,
    steel: 0,
    bauxite: 10,
    bucket: 1,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "水桶"],
  },
  {
    id: "A3",
    area: "1",
    name: "長時間対潜警戒",
    duration: 135,
    fuel: 120,
    ammo: 0,
    steel: 60,
    bauxite: 60,
    bucket: 1,
    torch: 0,
    devMat: 2,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域"],
  },
  {
    id: "A4",
    area: "1",
    name: "南西方面連絡線哨戒",
    duration: 110,
    fuel: 80,
    ammo: 120,
    steel: 0,
    bauxite: 100,
    bucket: 2,
    torch: 2,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "月常"],
  },
  {
    id: "A5",
    area: "1",
    name: "小笠原沖哨戒線",
    duration: 180,
    fuel: 0,
    ammo: 300,
    steel: 0,
    bauxite: 100,
    bucket: 3,
    torch: 0,
    devMat: 4,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "月常", "交戰"],
  },
  {
    id: "A6",
    area: "1",
    name: "小笠原沖戦闘哨戒",
    duration: 210,
    fuel: 100,
    ammo: 500,
    steel: 100,
    bauxite: 200,
    bucket: 0,
    torch: 0,
    devMat: 5,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第1海域", "月常", "交戰"],
  },

  // --- 第 2 海域：南西諸島海域 ---
  {
    id: "9",
    area: "2",
    name: "タンカー護衛任務",
    duration: 240,
    fuel: 350,
    ammo: 0,
    steel: 0,
    bauxite: 0,
    bucket: 2,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "燃料"],
  },
  {
    id: "10",
    area: "2",
    name: "強行偵察任務",
    duration: 90,
    fuel: 0,
    ammo: 50,
    steel: 0,
    bauxite: 40,
    bucket: 1,
    torch: 1,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域"],
  },
  {
    id: "11",
    area: "2",
    name: "ボーキサイト輸送任務",
    duration: 300,
    fuel: 0,
    ammo: 0,
    steel: 0,
    bauxite: 250,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "鋁土"],
  },
  {
    id: "12",
    area: "2",
    name: "資源輸送任務",
    duration: 480,
    fuel: 50,
    ammo: 250,
    steel: 200,
    bauxite: 50,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第2海域"],
  },
  {
    id: "13",
    area: "2",
    name: "鼠輸送作戦",
    duration: 240,
    fuel: 240,
    ammo: 300,
    steel: 0,
    bauxite: 0,
    bucket: 2,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "燃料", "彈藥"],
  },
  {
    id: "14",
    area: "2",
    name: "包囲陸戦隊撤収作戦",
    duration: 360,
    fuel: 0,
    ammo: 280,
    steel: 200,
    bauxite: 30,
    bucket: 1,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域"],
  },
  {
    id: "15",
    area: "2",
    name: "囮機動部隊支援作戦",
    duration: 720,
    fuel: 0,
    ammo: 0,
    steel: 300,
    bauxite: 400,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第2海域"],
  },
  {
    id: "16",
    area: "2",
    name: "艦隊決戦援護作戦",
    duration: 900,
    fuel: 500,
    ammo: 500,
    steel: 200,
    bauxite: 200,
    bucket: 0,
    torch: 2,
    devMat: 2,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域"],
  },
  {
    id: "B1",
    area: "2",
    name: "南西方面航空偵察作戦",
    duration: 35,
    fuel: 0,
    ammo: 0,
    steel: 20,
    bauxite: 30,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域"],
  },
  {
    id: "B2",
    area: "2",
    name: "敵泊地強襲反撃作戦",
    duration: 520,
    fuel: 300,
    ammo: 200,
    steel: 100,
    bauxite: 0,
    bucket: 2,
    torch: 0,
    devMat: 2,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "月常"],
  },
  {
    id: "B3",
    area: "2",
    name: "南西諸島離島哨戒作戦",
    duration: 170,
    fuel: 0,
    ammo: 100,
    steel: 100,
    bauxite: 180,
    bucket: 2,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第2海域", "月常"],
  },
  {
    id: "B4",
    area: "2",
    name: "南西諸島離島防衛作戦",
    duration: 450,
    fuel: 0,
    ammo: 0,
    steel: 1200,
    bauxite: 650,
    bucket: 0,
    torch: 0,
    devMat: 4,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "月常", "交戰"],
  },
  {
    id: "B5",
    area: "2",
    name: "南西諸島捜索撃滅戦",
    duration: 390,
    fuel: 500,
    ammo: 500,
    steel: 1000,
    bauxite: 750,
    bucket: 4,
    torch: 0,
    devMat: 0,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "月常", "交戰"],
  },
  {
    id: "B6",
    area: "2",
    name: "精鋭水雷戦隊夜襲",
    duration: 350,
    fuel: 600,
    ammo: 1000,
    steel: 600,
    bauxite: 600,
    bucket: 0,
    torch: 0,
    devMat: 5,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第2海域", "月常", "交戰"],
  },

  // --- 第 3 海域：北方海域 ---
  {
    id: "17",
    area: "3",
    name: "敵地偵察作戦",
    duration: 45,
    fuel: 70,
    ammo: 90,
    steel: 50,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "18",
    area: "3",
    name: "航空機輸送作戦",
    duration: 300,
    fuel: 0,
    ammo: 0,
    steel: 300,
    bauxite: 150,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "19",
    area: "3",
    name: "北号作戦",
    duration: 360,
    fuel: 400,
    ammo: 50,
    steel: 50,
    bauxite: 30,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "20",
    area: "3",
    name: "潜水艦哨戒任務",
    duration: 120,
    fuel: 0,
    ammo: 0,
    steel: 150,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "21",
    area: "3",
    name: "北方鼠輸送作戦",
    duration: 140,
    fuel: 320,
    ammo: 270,
    steel: 0,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域", "燃料", "彈藥"],
  },
  {
    id: "22",
    area: "3",
    name: "艦隊演習",
    duration: 180,
    fuel: 0,
    ammo: 10,
    steel: 0,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "23",
    area: "3",
    name: "航空戦艦運用演習",
    duration: 240,
    fuel: 0,
    ammo: 50,
    steel: 0,
    bauxite: 130,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第3海域"],
  },
  {
    id: "24",
    area: "3",
    name: "北方航路海上護衛",
    duration: 500,
    fuel: 500,
    ammo: 0,
    steel: 0,
    bauxite: 150,
    bucket: 1,
    torch: 0,
    devMat: 2,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第3海域", "燃料"],
  },

  // --- 第 4 海域：西方海域 ---
  {
    id: "25",
    area: "4",
    name: "通商破壊作戦",
    duration: 2400,
    fuel: 900,
    ammo: 0,
    steel: 500,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "26",
    area: "4",
    name: "敵母港空襲作戦",
    duration: 4800,
    fuel: 0,
    ammo: 0,
    steel: 0,
    bauxite: 900,
    bucket: 3,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第4海域"],
  },
  {
    id: "27",
    area: "4",
    name: "潜水艦通商破壊作戦",
    duration: 1200,
    fuel: 0,
    ammo: 0,
    steel: 800,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 2,
    screw: 0,
    boxS: 2,
    boxM: 0,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "28",
    area: "4",
    name: "西方海域封鎖作戦",
    duration: 1500,
    fuel: 0,
    ammo: 0,
    steel: 900,
    bauxite: 350,
    bucket: 0,
    torch: 0,
    devMat: 3,
    screw: 0,
    boxS: 0,
    boxM: 2,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "29",
    area: "4",
    name: "潜水艦派遣演習",
    duration: 1440,
    fuel: 0,
    ammo: 50,
    steel: 0,
    bauxite: 100,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "30",
    area: "4",
    name: "潜水艦派遣作戦",
    duration: 2880,
    fuel: 0,
    ammo: 50,
    steel: 0,
    bauxite: 100,
    bucket: 0,
    torch: 0,
    devMat: 3,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第4海域"],
  },
  {
    id: "31",
    area: "4",
    name: "海外艦との接触",
    duration: 120,
    fuel: 0,
    ammo: 30,
    steel: 0,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "32",
    area: "4",
    name: "遠洋練習航海",
    duration: 1440,
    fuel: 50,
    ammo: 50,
    steel: 50,
    bauxite: 50,
    bucket: 0,
    torch: 0,
    devMat: 3,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第4海域"],
  },
  {
    id: "D1",
    area: "4",
    name: "西方海域偵察作戦",
    duration: 120,
    fuel: 0,
    ammo: 20,
    steel: 20,
    bauxite: 100,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第4海域"],
  },
  {
    id: "D2",
    area: "4",
    name: "西方潜水艦作戦",
    duration: 600,
    fuel: 0,
    ammo: 0,
    steel: 400,
    bauxite: 800,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第4海域", "月常", "交戰"],
  },
  {
    id: "D3",
    area: "4",
    name: "欧州方面友軍との接触",
    duration: 720,
    fuel: 0,
    ammo: 800,
    steel: 500,
    bauxite: 400,
    bucket: 3,
    torch: 0,
    devMat: 0,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第4海域", "月常", "交戰"],
  },

  // --- 第 5 海域：南方海域 ---
  {
    id: "35",
    area: "5",
    name: "MO作戦",
    duration: 420,
    fuel: 0,
    ammo: 0,
    steel: 240,
    bauxite: 280,
    bucket: 0,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 2,
    boxM: 0,
    boxL: 0,
    tags: ["第5海域", "鋁土"],
  },
  {
    id: "36",
    area: "5",
    name: "水上機基地建設",
    duration: 540,
    fuel: 480,
    ammo: 0,
    steel: 200,
    bauxite: 200,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 2,
    boxL: 0,
    tags: ["第5海域", "燃料"],
  },
  {
    id: "37",
    area: "5",
    name: "東京急行",
    duration: 165,
    fuel: 0,
    ammo: 380,
    steel: 270,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第5海域", "彈藥", "鋼材"],
  },
  {
    id: "38",
    area: "5",
    name: "東京急行（弐）",
    duration: 175,
    fuel: 420,
    ammo: 0,
    steel: 200,
    bauxite: 0,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 1,
    boxM: 0,
    boxL: 0,
    tags: ["第5海域", "燃料", "鋼材"],
  },
  {
    id: "39",
    area: "5",
    name: "遠洋潜水艦作戦",
    duration: 1800,
    fuel: 0,
    ammo: 0,
    steel: 300,
    bauxite: 0,
    bucket: 2,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第5海域"],
  },
  {
    id: "40",
    area: "5",
    name: "水上機前線輸送",
    duration: 410,
    fuel: 300,
    ammo: 300,
    steel: 0,
    bauxite: 100,
    bucket: 1,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 3,
    boxM: 0,
    boxL: 0,
    tags: ["第5海域"],
  },
  {
    id: "E1",
    area: "5",
    name: "ラバウル方面艦隊進出",
    duration: 450,
    fuel: 0,
    ammo: 600,
    steel: 600,
    bauxite: 1000,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 2,
    tags: ["第5海域", "月常", "交戰"],
  },
  {
    id: "E2",
    area: "5",
    name: "強行鼠輸送作戦",
    duration: 185,
    fuel: 0,
    ammo: 480,
    steel: 0,
    bauxite: 0,
    bucket: 2,
    torch: 0,
    devMat: 0,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第5海域", "月常", "交戰"],
  },

  // --- 第 7 海域：南西海域 ---
  {
    id: "41",
    area: "7",
    name: "ブルネイ泊地沖哨戒",
    duration: 60,
    fuel: 100,
    ammo: 0,
    steel: 0,
    bauxite: 20,
    bucket: 1,
    torch: 0,
    devMat: 1,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第7海域"],
  },
  {
    id: "42",
    area: "7",
    name: "ミ船団護衛(一号船団)",
    duration: 480,
    fuel: 800,
    ammo: 0,
    steel: 0,
    bauxite: 200,
    bucket: 0,
    torch: 3,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 1,
    tags: ["第7海域", "月常"],
  },
  {
    id: "43",
    area: "7",
    name: "ミ船団護衛(二号船団)",
    duration: 720,
    fuel: 2000,
    ammo: 0,
    steel: 0,
    bauxite: 400,
    bucket: 0,
    torch: 0,
    devMat: 4,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第7海域", "月常", "交戰"],
  },
  {
    id: "44",
    area: "7",
    name: "航空装備輸送任務",
    duration: 600,
    fuel: 0,
    ammo: 200,
    steel: 0,
    bauxite: 800,
    bucket: 0,
    torch: 0,
    devMat: 4,
    screw: 0,
    boxS: 0,
    boxM: 0,
    boxL: 2,
    tags: ["第7海域", "月常"],
  },
  {
    id: "45",
    area: "7",
    name: "ボーキサイト船団護衛",
    duration: 200,
    fuel: 40,
    ammo: 0,
    steel: 0,
    bauxite: 220,
    bucket: 0,
    torch: 0,
    devMat: 0,
    screw: 0,
    boxS: 0,
    boxM: 1,
    boxL: 0,
    tags: ["第7海域"],
  },
  {
    id: "46",
    area: "7",
    name: "南西海域戦闘哨戒",
    duration: 210,
    fuel: 300,
    ammo: 0,
    steel: 150,
    bauxite: 380,
    bucket: 0,
    torch: 0,
    devMat: 3,
    screw: 1,
    boxS: 0,
    boxM: 0,
    boxL: 0,
    tags: ["第7海域", "月常", "交戰"],
  },
];
